//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RotinaServico
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RotinaServico.IRotina")]
    public interface IRotina
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRotina/ExecutarComando", ReplyAction="http://tempuri.org/IRotina/ExecutarComandoResponse")]
        System.Threading.Tasks.Task<string[]> ExecutarComandoAsync(string idComando, string idAmbienteOrigem, string idAmbienteDestino, string parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRotina/ExecutarTarefa", ReplyAction="http://tempuri.org/IRotina/ExecutarTarefaResponse")]
        System.Threading.Tasks.Task<string[]> ExecutarTarefaAsync(string idComando, string idAmbienteOrigem, string idAmbienteDestino, string parametros);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface IRotinaChannel : RotinaServico.IRotina, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class RotinaClient : System.ServiceModel.ClientBase<RotinaServico.IRotina>, RotinaServico.IRotina
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RotinaClient() : 
                base(RotinaClient.GetDefaultBinding(), RotinaClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IRotina.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RotinaClient(EndpointConfiguration endpointConfiguration) : 
                base(RotinaClient.GetBindingForEndpoint(endpointConfiguration), RotinaClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RotinaClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RotinaClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RotinaClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RotinaClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RotinaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string[]> ExecutarComandoAsync(string idComando, string idAmbienteOrigem, string idAmbienteDestino, string parametros)
        {
            return base.Channel.ExecutarComandoAsync(idComando, idAmbienteOrigem, idAmbienteDestino, parametros);
        }
        
        public System.Threading.Tasks.Task<string[]> ExecutarTarefaAsync(string idComando, string idAmbienteOrigem, string idAmbienteDestino, string parametros)
        {
            return base.Channel.ExecutarTarefaAsync(idComando, idAmbienteOrigem, idAmbienteDestino, parametros);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IRotina))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IRotina))
            {
                return new System.ServiceModel.EndpointAddress("http://mascate.fei.edu.br:20600/AtualDiaria/Rotina/srv");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return RotinaClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IRotina);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return RotinaClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IRotina);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IRotina,
        }
    }
}
